services: 
  db:
    container_name: postgres-db
    build: db/
    image: postgres:latest
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes: 
  pgdata: