name: Main Workflow
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]
  workflow_dispatch:
jobs:
  server_test_job:
    name: Server test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"  
      - name: "Build"
        run:
          dotnet build server/

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          test-container: "dotnet_test_container"
          test-command: 
            "dotnet test server/test/"
