name: Main Workflow
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]
jobs:
  server_test_job:
    name: Server test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Start docker container
        run: docker-compose up -d  

      - name: Wait for docker container to startup
        uses: jakejarvis/wait-action@master
        with:
          time: '8s'

      - name: Restore NuGet packages
        run: dotnet restore
        
      - name: Build
        run: dotnet build server/
        
      - name: Test
        run: dotnet test server/test/
